version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FOO: foo
    ports:
      - '8080:8080'
    environment:
      SECURITY_API_KEY: foo
    mem_limit: "2g"
    cpuset: "1"
    healthcheck:
      test: curl -Is localhost:8080 | head -n 1 | grep 200 || exit 1
      interval: 10s
      timeout: 2s
      retries: 10
